// webserver_about.cpp — /about stran za fancontrol
// Tehnična referenčna stran: opis projekta, hardware, logika, odločitve.
// Servirano kot inline String (ne gzip) — statična stran, redki klici.
// Navigacija: "ℹ About" link v headerju glavne strani → /about,
//             "← Nazaj" gumb na /about → /.

#include "webserver_about.h"
#include "config.h"

// ---------------------------------------------------------------------------
// Pomožni makro za čistejšo konkatenacijo dolgih HTML blokov
// ---------------------------------------------------------------------------
#define H(x) html += F(x)

// ---------------------------------------------------------------------------
// buildAboutPage() — vrne celoten HTML kot String (~25KB)
// ---------------------------------------------------------------------------
static String buildAboutPage() {
    String html;
    html.reserve(28000);

    // ── HEAD ────────────────────────────────────────────────────────────────
    H("<!DOCTYPE html><html lang=\"sl\"><head>"
      "<meta charset=\"UTF-8\">"
      "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
      "<title>FANCONTROL &#8212; O projektu</title>"
      "<style>"
      "*{box-sizing:border-box;margin:0;padding:0}"
      "body{background:#0d0d0d;color:#e0e0e0;font-family:monospace,system-ui;line-height:1.6}"
      "header{background:#1a1a1a;border-bottom:2px solid #00d4ff;padding:10px 20px;"
      "display:flex;justify-content:space-between;align-items:center}"
      "h1{color:#00d4ff;font-size:18px;letter-spacing:4px}"
      ".back{color:#00d4ff;text-decoration:none;font-size:12px;letter-spacing:1px;"
      "padding:6px 14px;border:1px solid #00d4ff;border-radius:4px;"
      "transition:background .2s}"
      ".back:hover{background:#00d4ff22}"
      "main{max-width:900px;margin:0 auto;padding:20px 16px}"
      ".page-title{color:#00d4ff;font-size:22px;letter-spacing:3px;"
      "margin-bottom:6px;text-transform:uppercase}"
      ".page-sub{font-size:11px;color:#555;margin-bottom:24px;letter-spacing:1px}"
      ".card{background:#1a1a1a;border:1px solid #2a2a2a;border-radius:8px;"
      "padding:16px 20px;margin-bottom:14px}"
      ".card-title{font-size:11px;color:#00d4ff;text-transform:uppercase;"
      "letter-spacing:2px;margin-bottom:10px;padding-bottom:6px;"
      "border-bottom:1px solid #2a2a2a}"
      "p{font-size:12px;color:#ccc;margin-bottom:8px}"
      "p:last-child{margin-bottom:0}"
      "b{color:#7ec8e3}"
      ".hl{color:#4caf50}"
      ".warn{color:#ff9500}"
      ".dim{color:#666;font-size:11px}"
      "pre{background:#0a1628;padding:10px 14px;border-radius:6px;"
      "font-size:11px;overflow-x:auto;color:#a8d8a8;margin:8px 0;line-height:1.5}"
      "code{background:#0f3460;padding:1px 5px;border-radius:3px;"
      "font-family:monospace;font-size:0.85em;color:#a8d8a8}"
      "a{color:#00d4ff}"
      "hr{border:none;border-top:1px solid #1e1e1e;margin:20px 0}"
      ".twoCol{display:flex;gap:14px;flex-wrap:wrap}"
      ".twoCol .card{flex:1;min-width:260px}"
      "</style></head><body>");

    // ── HEADER ──────────────────────────────────────────────────────────────
    H("<header>"
      "<div><h1>&#9650; FANCONTROL</h1></div>"
      "<a class=\"back\" href=\"/\">&#8592; Nazaj</a>"
      "</header>");

    // ── MAIN ────────────────────────────────────────────────────────────────
    H("<main>"
      "<div class=\"page-title\">&#9432; O projektu</div>"
      "<div class=\"page-sub\">Tehnična referenca &mdash; hardware, logika, odlo&#269;itve</div>");

    // ── 1. IZHODIŠČE ────────────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">Izhodišče projekta</div>"
      "<p>ACEMAGIC S1 je mini PC z Intel N100 procesorjem (Alder Lake-N, 6W TDP, do 25W burst)."
      " Naprava je kompaktna, tiha in namenjena stalnemu delovanju kot domači strežnik."
      " Problem: originalni ventilator (125mm, 3-pin PWM) ne dobi inteligentnega krmiljenja"
      " &mdash; BIOS ponuja samo &quot;Silent&quot; profil, ki pusti ventilator na fiksnih ~30%"
      " ne glede na temperaturo. Rezultat je ali pretirano hrupnost ali premalo hlajenja ob obremenitvah.</p>"
      "<p>Cilj projekta: ESP32-S3 mikrocontroler ki bere temperaturo zraka v ohišju (SHT30),"
      " porabo (INA219) in krmili ventilator prek PWM. Logika vključuje"
      " temperaturno krivuljo, adaptivno samo-učenje, watt feed-forward boost,"
      " DND nočni način, e-paper zaslon in popoln web vmesnik.</p>"
      "<p><b>Platforma:</b> ESP32-S3 TZT N16R8 &mdash; 16MB Flash, 8MB PSRAM OPI."
      " Dovolj za 7-dnevni graf buffer, obsežen RAM log in OTA posodobitve"
      " brez LittleFS kompleksnosti.</p>"
      "</div>");

    // ── 2. HARDWARE ─────────────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">Hardware &mdash; komponente in vezava</div>"
      "<p><b>Mikrokontroler: TZT ESP32-S3-N16R8</b><br>"
      "Dual-core Xtensa LX7 do 240MHz. 16MB Flash (particija za OTA brez LittleFS),"
      " 8MB OPI PSRAM za graf buffer in log. USB-C prek CH343P UART bridgea (GPIO43/44)"
      " &mdash; Serial monitor dela zanesljivo brez USB CDC konfiguracij."
      " Vgrajena RGB LED na GPIO48 (zahteva premostitev mostiča na PCB).</p>"
      "<p><b>GPIO dodelitev:</b></p>"
      "<pre>"
      "GPIO5   &rarr; PWM izhod &rarr; LR7843 MOSFET modul &rarr; ventilator (3-pin)\n"
      "GPIO8   &rarr; I2C SDA (SHT30 + INA219, naslov 0x44 / 0x40)\n"
      "GPIO9   &rarr; I2C SCL\n"
      "GPIO10  &rarr; SPI CS   (WeAct ePaper 2.9\" B/W)\n"
      "GPIO11  &rarr; SPI MOSI (WeAct pin 6, imenovan SDA na modulu)\n"
      "GPIO12  &rarr; SPI CLK  (WeAct pin 5, imenovan SCL na modulu)\n"
      "GPIO13  &rarr; ePaper D/C\n"
      "GPIO14  &rarr; ePaper RST\n"
      "GPIO15  &rarr; ePaper BUSY\n"
      "GPIO48  &rarr; RGB LED WS2812 (vgrajena)"
      "</pre>"
      "<p><b>SHT30 (I2C 0x44) &mdash; temperatura in vlažnost:</b><br>"
      "Senzor je nameščen znotraj ohišja ACEMAGIC S1 za merjenje temperature zraka"
      " na vsesalni strani ventilatorja. Točnost: &plusmn;0.3&deg;C, &plusmn;2% RH."
      " Priporočena namestitev: ne neposredno ob CPU ali PSU &mdash; meri ambient zrak, ne komponente.</p>"
      "<p><b>INA219 (I2C 0x40) &mdash; napetost in tok:</b><br>"
      "Nameščen v serijo z napajanjem mini PC (tipično 12V ali 19V adapter)."
      " Shunt upor: privzeto 0.1&Omega; (nastavljivo v kalibraciji). Meri napetost, tok in"
      " moč v realnem času. Poraba je ključni vhod za Watt Boost sistem.</p>"
      "<p><b>LR7843 MOSFET modul &mdash; PWM krmiljenje ventilatorja:</b><br>"
      "N-channel MOSFET z integriranim gate driverjem. 3-pin ventilator (GND, 12V, PWM)"
      " &mdash; ESP32 GPIO5 krmili gate, MOSFET preklaplja GND linijo ventilatorja."
      " PWM frekvenca 25kHz (Intel PWM standard za 4-pin ventilatorje, deluje tudi za 3-pin),"
      " nad slišnim pragom &mdash; brez piskov. Invertiran delovni cikel nastavljiv"
      " v web UI brez reseta (<code>reinitFanPwm()</code>).</p>"
      "<p><b>WeAct ePaper 2.9\" B/W &mdash; pasivni prikaz:</b><br>"
      "128&times;296px, SPI vmesnik. Pokončna orientacija. Prikazuje temperaturo, vlažnost,"
      " porabo, hitrost ventilatorja, čas, status WiFi in vreme. Partial refresh ob vsaki"
      " spremembi minute &mdash; brez moteče bele flash. Full refresh vsakih 60 minut"
      " za odstranitev ghostinga.</p>"
      "</div>");

    // ── 3. PWM IN FAN LOGIKA ────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">PWM krmiljenje in skala %user vs %PWM</div>"
      "<p>Sistem pozna dve skali, ki ju je pomembno razlikovati:</p>"
      "<pre>"
      "%user  = logična skala 0&ndash;100%, ki jo vidi uporabnik povsod\n"
      "%PWM   = fizikalna PWM vrednost 0&ndash;255 (8-bit)\n"
      "\n"
      "Konverzija (enkrat, v setFanPct()):\n"
      "  0%user  = 0%PWM     (motor izklopljen)\n"
      "  1%user  = 27%PWM    (fizikalni minimum za zanesljiv zagon)\n"
      "  100%user = 100%PWM  (polna hitrost)\n"
      "  Linearno vmes: PWM = 27 + (user-1) * 73/99"
      "</pre>"
      "<p><b>fanStartPct in fanStopPct</b> sta edini vrednosti v %PWM (ker opisujeta"
      " fizikalni minimum motorja). Vse ostalo &mdash; krivulja, DND, boost, dashboard,"
      " logi, ePaper &mdash; je v %user.</p>"
      "<p><b>Hysteresis in startup kick:</b><br>"
      "Ko fan% pade pod <code>fanStopPct</code> (%PWM), se motor ustavi. Ko naraste"
      " nad <code>fanStartPct</code> (%PWM), se sproži kick: motor za ~10 sekund"
      " (en senzorski cikel) dobi <code>fanStartPct</code> da se zanesljivo zažene,"
      " nato se spusti na željeno vrednost. Kick velja v avtomatskem in ročnem načinu.</p>"
      "<p><b>Max podnevi in DND max:</b><br>"
      "<code>fanMaxDayPct</code> omejuje maksimum med normalnim delovanjem."
      " <code>dndMaxPct</code> omejuje maksimum med DND (nočni tihi način)."
      " DND max sprejema samo 0% (motor ugasnjen) ali vrednost &ge; pragu zagona"
      " &mdash; vmesne vrednosti bi se obnašale enako kot stop prag in bi zavedle"
      " uporabnika.</p>"
      "</div>");

    // ── 4. TEMPERATURNA KRIVULJA ────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">Temperaturna krivulja &mdash; 6 točk</div>"
      "<p>Krivulja je definirana s 6 točkami (temp[&deg;C], fan[%user])."
      " Med točkami je linearna interpolacija. Privzete vrednosti kalibrirane"
      " za N100 mini PC s 125mm ventilatorjem:</p>"
      "<pre>"
      "Točka 0 (Mirovanje):          28&deg;C &rarr;   0%\n"
      "Točka 1 (Lahka obremenitev):  35&deg;C &rarr;   2%\n"
      "Točka 2 (Zmerna obremenitev): 40&deg;C &rarr;   7%\n"
      "Točka 3 (Višja obremenitev):  46&deg;C &rarr;  20%\n"
      "Točka 4 (Visoka obremenitev): 55&deg;C &rarr;  50%\n"
      "Točka 5 (Maksimum/zaščita):   65&deg;C &rarr; 100%"
      "</pre>"
      "<p>Pod točko 0 je ventilator ugasnjen. Nad točko 5 ostane na 100%."
      " Temperaturne meje con (<code>curveTemp[]</code>) se ne spreminjajo"
      " samodejno &mdash; jih nastavlja samo uporabnik.</p>"
      "<p>SVG graf krivulje v web UI (Tab VENTILATOR) je interaktiven &mdash;"
      " vsako točko je mogoče klikniti in urediti inline. Točke z visokim"
      " confidence so obrobljene zeleno, nizkim sivo, srednji zlato.</p>"
      "</div>");

    // ── 5. ADAPTIVNO UČENJE ─────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">Adaptivno samo-učenje krivulje (TEO algoritem)</div>"
      "<p>Sistem opazuje delovanje in postopno prilagaja fan% v vsaki točki krivulje"
      " na podlagi ravnovesnih opazovanj (TEO = Thermal Equilibrium Observer).</p>"
      "<p><b>Pogoji za ravnovesje (eno opazovanje):</b></p>"
      "<pre>"
      "- Temperatura stabilna: &plusmn;1&deg;C v zadnjih 15 minutah (90 vzorcev &times; 10s)\n"
      "- Fan% stabilen v celotnem oknu (ni sprememb)\n"
      "- Temperatura je blizu ene od 6 točk krivulje\n"
      "- Nobena zunanja intervencija (manual mode, boost, DND) ni aktivna"
      "</pre>"
      "<p><b>EMA posodabljanje točke:</b><br>"
      "Ko so pogoji izpolnjeni, se fan% točke posodobi z eksponentnim drsenjem:"
      " &alpha;=0.08 &mdash; 12 opazovanj za 50% vpliv novega podatka. Sistem se"
      " uči počasi in zanesljivo, brez hitrih nihanj.</p>"
      "<p><b>Confidence:</b><br>"
      "Vsako ravnovesno opazovanje poveča confidence točke za 1 (max 100)."
      " <span class=\"hl\">Prag aktivacije: 20</span> &mdash; ~5 ur realnega delovanja"
      " preden algoritem začne vplivati na točko. Pod pragom ostane privzeta vrednost.</p>"
      "<p><b>Zaklepanje točk:</b><br>"
      "Vsaka točka je neodvisno zaklenljiva &mdash; algoritem zaklenjenih točk ne"
      " posodablja. Zaklep ohranimo ob resetu učenja. Ročni vnos vrednosti točke"
      " jo implicitno zaklene (gumb v SVG grafu ali tabela vrednosti).</p>"
      "<p><b>Reset učenja:</b><br>"
      "Ponastavi EMA vrednosti na privzete in confidence na 0. Zaklep per točka ostane."
      " Dostopno prek gumba &quot;Reset učenja&quot; v Tab VENTILATOR.</p>"
      "<p><span class=\"warn\">Opomba:</span> Adapt algoritem dobi fan% vključno z"
      " aktivnim boostom &mdash; uči se realnih vrednosti, ne teoretičnih krivulje.</p>"
      "</div>");

    // ── 6. WATT BOOST ───────────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">Watt Feed-Forward Boost</div>"
      "<p>Temperaturni senzor (SHT30) ima termično zakasnitev &mdash; temperatura"
      " ambient zraka se odzove na CPU burst šele po 30&ndash;90 sekundah. Boost"
      " sistem reagira na porabo (INA219) brez čakanja na temperaturni odziv.</p>"
      "<p><b>Princip delovanja:</b></p>"
      "<pre>"
      "1. Poraba preseže prag (privzeto 17W) za vsaj 15s (BOOST_ACTIVATE_MS)\n"
      "2. Boost se aktivira: fan% se takoj dvigne za boost vrednost (privzeto +10%)\n"
      "3. Po boostEvalMs (20s) se boost začne izzvanjati (fade)\n"
      "4. Po boostLearnMs (120s) sistem oceni dT/min in prilagodi boost%\n"
      "5. Ob padcu porabe pod prag se boost deaktivira"
      "</pre>"
      "<p><b>Samoučenje boost%:</b><br>"
      "Po 120s eval okna sistem izmeri temperaturni gradient (dT/min). Če je dT visok"
      " (temperatura narašča kljub boostu), se boost% poveča. Če je nizek, se zmanjša."
      " EMA &alpha;=0.1 za postopno prilagajanje. Zaklep (<code>boostLocked</code>)"
      " onemogoči samoučenje in ohrani ročno nastavljeno vrednost.</p>"
      "<p><b>Ločitev dveh časovnih parametrov</b> (odločitev v1.2.0):<br>"
      "<code>boostEvalMs</code> = fade timer (20s) &mdash; čas izzvenjanja po deaktivaciji.<br>"
      "<code>boostLearnMs</code> = eval okno (120s) &mdash; čas za oceno dT/min.<br>"
      "Razlog ločitve: 20s dT/min formula bi pomnoževala temperaturni šum SHT30 (&plusmn;0.3&deg;C)"
      " s faktorjem 3 &mdash; nestabilne odločitve samoučenja. 120s dá 12 meritev in stabilen signal.</p>"
      "<p><b>Interakcija s krivuljo:</b><br>"
      "Boost dodaja k izhodu krivulje, ne ga nadomešča. Na SVG grafu krivulje"
      " je boost prikazan kot oranžna puščica navzgor od trenutne temperature.</p>"
      "</div>");

    // ── 7. DND ──────────────────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">DND &mdash; Do Not Disturb (nočni tihi način)</div>"
      "<p>Med DND urami (privzeto 22:00&ndash;06:00) je hitrost ventilatorja omejena"
      " na <code>dndMaxPct</code> (privzeto 20%user). Namen: manj hrupa ponoči ko je"
      " mini PC v idle ali lahki obremenitvi.</p>"
      "<p><b>Prioritete:</b><br>"
      "Ročni način (<em>manual</em>) popolnoma preglasi DND &mdash; DND velja samo za"
      " avtomatski način. Boost je prav tako oproščen DND omejitve v fazi aktivacije"
      " &mdash; zaščita komponente ima prednost pred tišino.</p>"
      "<p><b>DND max validacija:</b><br>"
      "Vrednost 1&ndash;8%user je nedovoljena &mdash; tako nizke vrednosti bi se"
      " obnašale enako kot stop prag (hysteresis bi jih dvignil) in bi zavajale"
      " uporabnika. Dovoljeno je 0% (motor ugasnjen med DND) ali &ge;9%user"
      " (dinamično glede na <code>fanStartPct</code>).</p>"
      "<p><b>Sunrise/sunset integracija:</b><br>"
      "DND ure so fiksne (ne sunrise/sunset based) &mdash; preprosto in predvidljivo."
      " Sunrise/sunset se uporablja za ePaper prikaz in <code>isNight</code> flag"
      " za vremenski widget, ne za DND logiko.</p>"
      "</div>");

    // ── 8. SENZORJI IN KALIBRACIJA ──────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">Senzorji in kalibracija</div>"
      "<p><b>SHT30 kalibracija:</b><br>"
      "<code>tempOffset</code> in <code>humOffset</code> sta aditivna offseta ki se"
      " prištejeta k vsaki meritvi. Primer: če SHT30 meri 2&deg;C preveč zaradi"
      " bližine grelnih elementov, nastavi <code>tempOffset = -2.0</code>."
      " Vrednosti so shranjene v NVS in preživijo reboot.</p>"
      "<p><b>INA219 kalibracija:</b><br>"
      "<code>shuntOhms</code>: vrednost shunt upora (privzeto 0.1&Omega;)."
      " Natančna vrednost vpliva na točnost meritve toka. Izmeri z multimetrom.<br>"
      "<code>currentCorr</code>: multiplikativni korekcijski faktor toka (privzeto 1.0)."
      " Za fino ujemanje z referenčnim merilnikom.</p>"
      "<p><b>Inicializacija in retry:</b><br>"
      "Senzorja se inicializirata ob bootu. Ob neuspehu (napaka I2C) se nastavi"
      " <code>ERR_SHT30</code> ali <code>ERR_INA219</code> bit v error bitmaski."
      " Vsake 60s se sproži <code>retrySensors()</code> dokler inicializacija ne uspe."
      " Brez zamrznitve sistema &mdash; ostale funkcije tečejo naprej.</p>"
      "<p><b>Peak trackerji:</b><br>"
      "<code>peakTemp</code> in <code>peakFan</code> sledita absolutnemu maximumu"
      " od zadnjega reseta, shranjeno v NVS. Peak poraba (<code>peakWatt</code>) ima"
      " razpolovno dobo 14 dni &mdash; avtomatsko se zmanjšuje da ostane relevantna."
      " Floor je 5W (bar ne postane nesmiselno majhen).</p>"
      "</div>");

    // ── 9. GRAF IN HISTORIA ─────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">Graf in povijest meritev</div>"
      "<p><b>Buffer arhitektura:</b><br>"
      "60480 točk &times; 24 bytes = ~1.45MB v PSRAM OPI. Interval: 10 sekund."
      " Pokritost: 7 dni neprekinjeno. Timestamp je Unix čas (ezTime <code>UTC.now()</code>)."
      " Po polnitvi buffer kroži &mdash; najstarejše točke se prepišejo.</p>"
      "<p><b>Decimacija na ESP32:</b><br>"
      "API <code>/api/history?maxPts=800</code> vrne &le;800 točk z bucket averaging"
      " (ne vsaka N-ta točka). Vsak bucket je povprečje vseh točk v časovnem oknu."
      " Cap je 2000 točk za robustnost. Surovi podatki dostopni samo prek"
      " <code>/api/history/csv</code> streaming endpointa.</p>"
      "<p><b>Glajenje na clientu:</b><br>"
      "Moving average v browserju (ne ESP32). Watt dobi 2&times; večji N ker ima"
      " najhitrejše nihanje (CPU bursti). Toggle &quot;Glajenje&quot; prikaže surove"
      " podatke za debug. <code>_rawData</code> vedno hrani neglajene vrednosti."
      " Glajeni gredo samo v uPlot.</p>"
      "<p><b>uPlot knjižnica:</b><br>"
      "45KB, servirana iz PROGMEM (<code>/uplot.js</code>, <code>/uplot.css</code>)"
      " z 24h Cache-Control. Brez interneta &mdash; grafi delujejo popolnoma lokalno."
      " Chart.js zamenjan (220KB CDN, laganje pri 10000+ točkah).</p>"
      "<p><b>Interakcija:</b><br>"
      "Scroll = pan (premik v zgodovino). Ctrl+Scroll = zoom (menjava perioda)."
      " Klik+drag = zoom na izbrano območje. Dvojni klik = LIVE mode."
      " Gumbi PAN/ZOOM so fallback za naprave brez kolesca. Period gumbi:"
      " 10min / 1h / 6h / 24h / 3d / 7d / VSE.</p>"
      "</div>");

    // ── 10. WIFI IN OMREŽJE ─────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">WiFi &mdash; multi-slot, roaming, stabilnost</div>"
      "<p><b>Statični IP:</b><br>"
      "Konfiguriran v <code>wifi_config.h</code> (ni v gitrepo &mdash; vsebuje gesla)."
      " Statični IP zagotavlja da je naprava vedno dosegljiva na istem naslovu"
      " brez DHCP odvisnosti.</p>"
      "<p><b>5 WiFi slotov:</b><br>"
      "Prioritetna lista omrežij. Ob zagonu ali reconnectu se preizkušajo po vrstnem"
      " redu. Vrstni red je prioriteta &mdash; nastavljiv v web UI Tab WIFI."
      " Gesla se nikoli ne vrnejo prek API-ja (<code>/api/wifi/networks</code>"
      " vrne samo SSID, enabled flag in hasPass bool).</p>"
      "<p><b>mDNS:</b> <code>http://fan.local</code> &mdash; dostop brez pomnjenja IP naslova.</p>"
      "<p><b>Roaming reconnect:</b><br>"
      "Vsakih 60 minut se izvede tihi disconnect &rarr; scan &rarr; reconnect za"
      " iskanje boljše mesh točke. RSSI-triggered reconnect je bil zavrnjen &mdash;"
      " RSSI &lt; -85 dBm je normalen prehodni pojav v Asus mesh okolju in bi"
      " povzročal nepotrebne prekinitve.</p>"
      "<p><b>WiFi scan strategija:</b><br>"
      "Kanalski scan (1&ndash;13 po vrsti, 150ms/kanal) &mdash; workaround za ESP-IDF"
      " bug kjer <code>rec-&gt;primary</code> vedno vrne connected channel namesto"
      " dejanskega kanala AP-ja. Deduplikacija po BSSID s shranjevanjem najboljšega RSSI.</p>"
      "<p><b>WiFi health:</b><br>"
      "NTP fail counter: 3 zaporedne napake sprožijo WiFi reconnect (pogosto je vzrok"
      " za NTP timeout prav pokvarjena WiFi seja). Watchdog vsakih 10 minut preveri"
      " <code>WiFi.status()</code> in reconnecta če ni povezan.</p>"
      "<p><b>Brez avtentikacije:</b><br>"
      "Vsi endpointi so dostopni brez gesla. Zavestna odločitev za domačo lokalno mrežo."
      " OTA je prav tako odprt. Tveganje je sprejemljivo v trusted home networku.</p>"
      "</div>");

    // ── 11. NTP IN ČAS ──────────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">NTP sinhronizacija in timezone</div>"
      "<p>Knjižnica ezTime (<code>myTZ.setLocation(\"Europe/Ljubljana\")</code>)."
      " Timezone string: <code>CET-1CEST,M3.5.0,M10.5.0/3</code>."
      " Polletni čas (CEST/CET) se preklopi avtomatično.</p>"
      "<p><b>Boot sekvenca NTP:</b><br>"
      "Po uspešnem WiFi connectu se pokliče <code>syncNTP()</code> z"
      " <code>waitForSync(8)</code> (8s timeout). Preizkusi vse nastavljene"
      " NTP strežnike po vrsti. Ob neuspehu se nastavi <code>ERR_NTP</code>"
      " in retry vsake 5 minute dokler ni sinhroniziran.</p>"
      "<p><b>Timestamp za graf:</b><br>"
      "<code>UTC.now()</code> iz ezTime &mdash; ne <code>time(nullptr)</code>."
      " Razlog: ezTime ne inicializira POSIX ure avtomatično. Brez NTP vrne"
      " monotoni timestamp iz <code>millis()/1000</code>.</p>"
      "<p><b>Re-sync:</b> Vsakih 30 minut za kompenziracijo drifta RTC-ja.</p>"
      "</div>");

    // ── 12. VREMENSKI API ────────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">Vremenski API &mdash; Open-Meteo</div>"
      "<p>Open-Meteo je brezplačen, brez API ključa, WMO standard kode."
      " Koordinate konfigurirane v <code>config.h</code>"
      " (<code>WEATHER_LAT=46.05</code>, <code>WEATHER_LON=14.51</code> za Ljubljano)."
      " Interval fetchanja: 30 minut. Potrebuje aktivno internetno povezavo.</p>"
      "<p><b>Pridobljeni podatki:</b><br>"
      "Zunanja temperatura, relativna vlažnost, WMO weather code (ikona na ePaperju),"
      " čas sončnega vzhoda in zahoda (za <code>isNight</code> flag).</p>"
      "<p><b>Lokalni izračun sunrise/sunset:</b><br>"
      "Implementiran v <code>suntime.cpp</code> (Duffett-Smith formula, &plusmn;1&ndash;2 min"
      " natančnost, brez API odvisnosti). Open-Meteo API sunrise/sunset se upošteva"
      " ko je na voljo &mdash; lokalni izračun je fallback in hkrati vrednost pri prvem"
      " prikazu preden pride API odgovor.</p>"
      "<p><b>JSON filter:</b><br>"
      "Samo <code>current</code> in <code>daily[0]</code> polja za minimalen prenos."
      " PSRAM buffer 4KB za HTTP response (ne heap &mdash; zaščita pred fragmentacijo).</p>"
      "<p><b>isNight logika:</b><br>"
      "Izračunano iz sunrise/sunset HH:MM in trenutnega časa timezone-a."
      " Vpliva na ePaper prikaz (luna/sonce ikona) in barvo LED.</p>"
      "</div>");

    // ── 13. EPAPER ZASLON ───────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">ePaper zaslon &mdash; WeAct 2.9\" B/W</div>"
      "<p>128&times;296px, SPI, pokončna orientacija. Nizka poraba v mirovanju"
      " (e-ink ohranja sliko brez toka). Prikaže:</p>"
      "<pre>"
      "- Temperatura in vlažnost (SHT30)\n"
      "- Poraba [W] z bar grafom (INA219, peak z razpolovno dobo)\n"
      "- Hitrost ventilatorja [%] z bar grafom\n"
      "- Čas (HH:MM) in datum\n"
      "- Zunanja temperatura in vlažnost (Open-Meteo)\n"
      "- Vremenska ikona (WMO koda)\n"
      "- Sunrise/sunset čas\n"
      "- WiFi RSSI indikator\n"
      "- Error ikone ob napakah senzorjev"
      "</pre>"
      "<p><b>Refresh strategija:</b><br>"
      "<code>setPartialWindow(0,0,128,296)</code> za partial refresh &mdash; odpravi"
      " inverzni beli flash ki ga povzroča <code>setFullWindow()</code>."
      " Trigger: ob vsaki spremembi minute (ali 60s timer brez NTP)."
      " Full refresh vsakih 60 minut (<code>EPD_FULL_REFRESH_INTERVAL_MIN</code>)"
      " za odstranitev ghostinga ki se kopiči s partial osvežitvami.</p>"
      "<p><b>BUSY pin:</b><br>"
      "<code>INPUT_PULLUP</code> na GPIO15 &mdash; floating pin brez priključenega"
      " zaslona bere HIGH &rarr; 3s timeout &rarr; <code>initDisplay()</code>"
      " vrne <code>false</code> &rarr; <code>ERR_DISPLAY</code>. Retry vsake 5 minute.</p>"
      "<p><b>WeAct pin poimenovanje:</b><br>"
      "Modul imenuje SPI pine z I2C imeni: <code>SDA=MOSI</code>, <code>SCL=CLK</code>."
      " To je samo poimenovanje na silkscreenu &mdash; električno so to standardni SPI pini.</p>"
      "</div>");

    // ── 14. SERVER MONITOR ──────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">Server Monitor &mdash; TCP port scanning</div>"
      "<p>Mini PC monitor preverja ali so ključni servisi živi prek TCP connect"
      " testov. Interval: 5 minut (7 portov &times; 500ms timeout = 3.5s blokiranja"
      " loopha &mdash; sprejemljivo za 5-minutni interval).</p>"
      "<p><b>Privzeta lista portov (nastavljivo v web UI):</b></p>"
      "<pre>"
      "Port  80  HTTP\n"
      "Port 443  HTTPS\n"
      "Port  25  SMTP\n"
      "Port 587  SMTP-S\n"
      "Port 465  SMTPS\n"
      "Port 993  IMAP-S\n"
      "Port 9443 Axigen (mail server web admin)\n"
      "+ 2 opcijska prosta slota"
      "</pre>"
      "<p><b>Napajanje:</b><br>"
      "INA219 meri porabo v realnem času. Prag (privzeto 3W) določa ali je mini PC"
      " vklopljen ali izklopljen. Prikaz na dashboardu: ON/OFF ikona. Kombinacija"
      " powered + port status dá celostno sliko servisa.</p>"
      "<p>IP naslov monitorenega serverja je nastavljiv v Tab KALIBRACIJA.</p>"
      "</div>");

    // ── 15. OTA POSODOBITVE ─────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">OTA posodobitve firmware</div>"
      "<p>Over-The-Air flash prek web UI brez USB kabla. Tab SISTEM &rarr; OTA Update"
      " &rarr; izberi <code>.bin</code> datoteko &rarr; Naloži firmware.</p>"
      "<p><b>Postopek:</b></p>"
      "<pre>"
      "1. V PlatformIO: pio run -e esp32s3 --target buildfs (ali samo Build)\n"
      "2. Kopiraj .pio/build/esp32s3/firmware.bin\n"
      "3. Web UI: SISTEM &rarr; OTA Update &rarr; izberi firmware.bin\n"
      "4. Progress bar &rarr; naprava se samodejno restartira\n"
      "5. Stran se osveži po 5.5s"
      "</pre>"
      "<p><b>Particijska shema:</b><br>"
      "<code>partitions_16mb_ota.csv</code> &mdash; prilagojena za 16MB Flash."
      " Dve app particiji za OTA (app0 + app1), NVS, brez LittleFS."
      " Dovolj prostora za rast kode brez kompromisov.</p>"
      "<p><b>Brez preverjanja verzije:</b><br>"
      "ESP32 Update API sprejme katerikoli veljaven binary. Preveritev na uporabniku."
      " Ob napaki pri flashing se naprava ne zažene iz slabe slike &mdash;"
      " ostane na prejšnji particiji.</p>"
      "</div>");

    // ── 16. API REFERENCA ───────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">API referenca &mdash; HTTP endpointi</div>"
      "<p><b>GET endpointi:</b></p>"
      "<pre>"
      "GET /                    Glavna SPA stran (gzip, PROGMEM)\n"
      "GET /about               Ta stran\n"
      "GET /uplot.js            uPlot knjižnica (PROGMEM, cache 24h)\n"
      "GET /uplot.css           uPlot CSS (PROGMEM, cache 24h)\n"
      "GET /api/data            JSON: temp, hum, volt, watt, fan, uptime, heap...\n"
      "GET /api/history         JSON točke za graf (?from=ts&amp;to=ts&amp;maxPts=N)\n"
      "GET /api/history?format=csv  Streaming CSV download celotnega bufferja\n"
      "GET /api/history/csv     Streaming CSV (alternativna pot)\n"
      "GET /api/fansettings     JSON: krivulja, DND, boost, hysteresis\n"
      "GET /api/calsettings     JSON: temp/hum offset, shunt, pwm\n"
      "GET /api/fan/manual      JSON: manual mode stanje\n"
      "GET /api/monitor         JSON: port status, powered flag\n"
      "GET /api/monitorsettings JSON: IP, watt prag, port lista\n"
      "GET /api/led             JSON: LED enabled\n"
      "GET /api/log             JSON: zadnjih 50 log vnosov\n"
      "GET /api/log?format=txt  Streaming TXT download celotnega loga\n"
      "GET /api/log/all         Streaming JSON: vsi log vnosi\n"
      "GET /api/wifi/status     JSON: connected, SSID, RSSI, scan rezultati\n"
      "GET /api/wifi/history    JSON: zadnjih 10 WiFi eventov\n"
      "GET /api/wifi/networks   JSON: sloti (brez gesel)"
      "</pre>"
      "<p><b>POST endpointi:</b></p>"
      "<pre>"
      "POST /save/fan           Shrani fan nastavitve (JSON body)\n"
      "POST /save/cal           Shrani kalibracije (JSON body)\n"
      "POST /save/monitor       Shrani monitor nastavitve (JSON body)\n"
      "POST /save/pwmcal        Shrani PWM frekvenco in invert (JSON body)\n"
      "POST /adapt/reset        Reset adaptivnega učenja\n"
      "POST /api/fan/manual     Nastavi ročni način (JSON: manual, pct)\n"
      "POST /api/led            Nastavi LED (JSON: enabled)\n"
      "POST /api/restart        Restart naprave\n"
      "POST /api/settings/reset Ponastavi nastavitve na privzete + restart\n"
      "POST /api/peaks/reset    Ponastavi peak temp in fan\n"
      "POST /api/log/clear      Počisti RAM log\n"
      "POST /api/wifi/slots     Shrani WiFi slote (JSON: slots array)\n"
      "POST /api/wifi/reconnect Ročni WiFi reconnect\n"
      "POST /api/wifi/scan      Sproži WiFi scan\n"
      "POST /api/wifi/connect   Poveži na specifičen SSID (?ssid=X)\n"
      "POST /api/factory_reset  Ponastavi WiFi slote na factory defaults\n"
      "POST /update             OTA flash (multipart/form-data)"
      "</pre>"
      "</div>");

    // ── 17. SOFTWARE ARHITEKTURA ─────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">Software arhitektura &mdash; moduli in loop()</div>"
      "<p><b>Struktura datotek:</b></p>"
      "<pre>"
      "src/\n"
      "&#9500;&#9472; main.cpp          setup(), loop(), koordinacija\n"
      "&#9500;&#9472; config.h          Vsi pini, konstante, enum-i\n"
      "&#9500;&#9472; globals.h/cpp     Globalne strukture, NVS load/save\n"
      "&#9500;&#9472; sensors.h/cpp     SHT30 + INA219 branje, retry logika\n"
      "&#9500;&#9472; fan.h/cpp         PWM krmiljenje, hysteresis, kick, manual\n"
      "&#9500;&#9472; fan_adapt.h/cpp   TEO adaptivni algoritem\n"
      "&#9500;&#9472; fan_boost.h/cpp   Watt Feed-Forward Boost\n"
      "&#9500;&#9472; graph_store.h/cpp PSRAM graf buffer, decimacija\n"
      "&#9500;&#9472; logging.h/cpp     RAM log (PSRAM, 10000 vnosov)\n"
      "&#9500;&#9472; monitor.h/cpp     TCP port scanner\n"
      "&#9500;&#9472; display.h/cpp     ePaper WeAct 2.9\" driver\n"
      "&#9500;&#9472; led.h/cpp         RGB LED WS2812 stanja\n"
      "&#9500;&#9472; suntime.h/cpp     Lokalni sunrise/sunset izračun\n"
      "&#9500;&#9472; webserver.h/cpp   AsyncWebServer, SPA HTML, vsi endpointi\n"
      "&#9500;&#9472; webserver_about.h/cpp  Ta stran (/about)\n"
      "&#9500;&#9472; uplot_assets.h    uPlot JS+CSS v PROGMEM\n"
      "&#9492;&#9472; wifi_config.h     WiFi gesla (gitignore)"
      "</pre>"
      "<p><b>loop() prioritetni vrstni red:</b></p>"
      "<pre>"
      "1. Senzorji (vsakih 10s)  &rarr; SHT30 + INA219 branje\n"
      "2. Fan logika              &rarr; krivulja + adapt + boost + hysteresis\n"
      "3. Graf buffer (vsakih 10s)&rarr; shrani točko v PSRAM\n"
      "4. Display (ob spremembi)  &rarr; ePaper partial/full refresh\n"
      "5. Monitor (vsakih 5min)   &rarr; TCP port scan\n"
      "6. Weather (vsakih 30min)  &rarr; Open-Meteo HTTP fetch\n"
      "7. handleWebserver()       &rarr; NTP, WiFi watchdog, roaming"
      "</pre>"
      "<p><b>Threading:</b><br>"
      "ESP32-S3 dual-core. Web server (AsyncWebServer) teče na Core 0 v ozadju."
      " Senzorji, fan, graf in ePaper tečejo na Core 1 v <code>loop()</code>."
      " Mutex <code>dataMux</code> ščiti <code>sensorData</code> in <code>weatherData</code>"
      " pred hkratnim dostopom.</p>"
      "<p><b>Hardware WDT: 120s</b> &mdash; konzervativno, samo zaščita pred popolno"
      " zamrznitvijo. Krajši timeout bi povzročal restate (ePaper full refresh ~3s,"
      " WiFi scan ~7s, NTP sync ~8s).</p>"
      "</div>");

    // ── 18. NVS SHRANJEVANJE ─────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">NVS shranjevanje &mdash; Preferences</div>"
      "<p>NVS (Non-Volatile Storage) je ESP-IDF mehanizem za trajno shranjevanje"
      " v Flash. Namespace: <code>fanctrl</code> (glavne nastavitve),"
      " <code>fanadapt</code> (adaptivno učenje), <code>fanboost</code> (boost state)."
      " Preživi reboot in power loss med pisanjem (atomični commiti)."
      " Endurance: ~10.000 pisalnih ciklov na ključ.</p>"
      "<p><b>Ključne vrednosti v NVS:</b></p>"
      "<pre>"
      "fanctrl namespace:\n"
      "  curveTemp[0..5]    float   Temperaturne meje krivulje\n"
      "  curvePct[0..5]     uint8   Fan % krivulje\n"
      "  curveLocked[0..5]  bool    Zaklep točk\n"
      "  tempOffset         float   SHT30 temp kalibracija\n"
      "  humOffset          float   SHT30 hum kalibracija\n"
      "  shuntOhms          float   INA219 shunt [ohm]\n"
      "  currentCorr        float   INA219 korekcija\n"
      "  fanStartPct        uint8   Zagon prag [%PWM]\n"
      "  fanStopPct         uint8   Stop prag [%PWM]\n"
      "  dndEnabled         bool    DND vklopljen\n"
      "  dndFrom/dndTo      uint8   DND ure\n"
      "  dndMaxPct          uint8   DND max [%user]\n"
      "  fanMaxDayPct       uint8   Max podnevi [%user]\n"
      "  fanPwmFreq         uint32  PWM frekvenca [Hz]\n"
      "  fanPwmInvert       bool    Invertiran PWM\n"
      "  ledEnabled         bool    RGB LED\n"
      "  monitorIp          string  Monitor IP\n"
      "  peakTemp           float   Peak temperatura\n"
      "  peakFan            uint8   Peak fan %\n"
      "  peakWatt           float   Peak poraba\n"
      "  ws0..4_ssid/pass   string  WiFi sloti\n"
      "\n"
      "fanadapt namespace:\n"
      "  confidence[0..5]   uint8   Confidence per točka\n"
      "\n"
      "fanboost namespace:\n"
      "  boostPct           uint8   Boost vrednost\n"
      "  boostLocked        bool    Zaklep boost"
      "</pre>"
      "</div>");

    // ── 19. GZIP IN MAIN HTML ────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">Gzip kompresija glavne strani</div>"
      "<p>Glavna SPA stran (~76KB HTML) je pred-kompresirana v gzip byte array"
      " (<code>webserver_html_gz.h</code>) s PlatformIO pre-build skriptom"
      " <code>scripts/generate_html_gz.py</code>.</p>"
      "<p><b>Rezultat:</b> 76KB &rarr; 19KB (75% prihranek). Servirana z"
      " <code>Content-Encoding: gzip</code> header. Browser dekompresira transparentno.</p>"
      "<p><b>Workflow:</b><br>"
      "<code>extra_scripts = pre:scripts/generate_html_gz.py</code> v"
      " <code>platformio.ini</code> zagotovi da se header regenerira ob vsakem"
      " <code>pio run</code>. <code>webserver_html_gz.h</code> je v"
      " <code>.gitignore</code> &mdash; generiran artifact, vir je"
      " <code>MAIN_HTML[]</code> string v <code>webserver.cpp</code>.</p>"
      "<p>Stran <code>/about</code> ni gzip kompresirana &mdash; servirano kot"
      " navaden inline String iz PROGMEM. Staticna stran z redkimi klici;"
      " dodatna kompleksnost gzip procesa ni opravičljiva.</p>"
      "</div>");

    // ── 20. PSRAM STRATEGIJA ─────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">PSRAM strategija &mdash; TZT ESP32-S3 N16R8</div>"
      "<p>8MB OPI PSRAM. Rezervirani bloki:</p>"
      "<pre>"
      "Graf buffer:   60480 &times; 24B  = ~1.45MB\n"
      "RAM Log:       10000 &times; 143B = ~1.43MB\n"
      "Weather buf:   4096B            =  0.004MB\n"
      "HTTP buferji:  ~8 &times; 2KB   =  0.016MB\n"
      "                               ___________\n"
      "Skupaj:                        ~2.9MB / 8MB (36%)"
      "</pre>"
      "<p>Vsi veliki alokacije so z <code>ps_malloc()</code> &mdash; ne heap."
      " Heap ostane prost za ArduinoJson, String operacije in AsyncWebServer."
      " <code>ESP.getFreePsram()</code> in <code>ESP.getFreeHeap()</code> sta"
      " vidna v Tab SISTEM &rarr; Sistem.</p>"
      "</div>");

    // ── 21. TROUBLESHOOTING ──────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">Troubleshooting &mdash; diagnoza s Serial monitorjem</div>"
      "<p>Poveži USB-C (CH343P port, ne native USB) in odpri Serial monitor na"
      " <b>115200 baud</b>. Ob zagonu pričakuješ:</p>"
      "<pre>"
      "[BOOT] fancontrol v1.x.x\n"
      "[SHT30] OK temp=24.3C hum=48.2%\n"
      "[INA219] OK volt=12.02V amp=0.312A watt=3.75W\n"
      "[EPAPER] OK init\n"
      "[WIFI] Connecting [slot 0]: MyNetwork\n"
      "[WIFI] Connected: 192.168.x.x  RSSI: -55 dBm\n"
      "[NTP] Synced: 12.06.2026 14:23:01\n"
      "[WEB] Server started on 192.168.x.x\n"
      "[WX] Vreme OK: 18.5 degC  65%  wxCode=2"
      "</pre>"
      "<p><b>Pogosti problemi:</b></p>"
      "<p><b>SHT30 ne deluje</b> (<code>ERR_SHT30</code>):<br>"
      "Preveri I2C vezavo (SDA=GPIO8, SCL=GPIO9), napajanje 3.3V, I2C naslov 0x44."
      " Za scan: temp <code>i2c_scanner</code> sketch.</p>"
      "<p><b>INA219 ne deluje</b> (<code>ERR_INA219</code>):<br>"
      "Preveri I2C naslov 0x40. Preveri da je shunt upor pravilno v seriji z napajanjem."
      " Shunt &ge; 0.01&Omega;.</p>"
      "<p><b>ePaper ne kaže ničesar ali kaže artefakte:</b><br>"
      "Preveri SPI vezavo (posebej MOSI=GPIO11, CLK=GPIO12). WeAct je poimenoval"
      " SDA/SCL &mdash; pri žičenju poglej config.h za pravilne GPIO."
      " Ob trajnem ghostingu: sproži manual full refresh (ne prek UI, reset naprave).</p>"
      "<p><b>Ventilator ne reagira:</b><br>"
      "Preveri GPIO5 &rarr; LR7843 MOSFET vezavo. Preizkusi ročni način (Tab VENTILATOR"
      " &rarr; Ročno upravljanje). Preveri ali je <code>fanPwmInvert</code>"
      " nastavljen pravilno za tvoj MOSFET modul.</p>"
      "<p><b>Graf prazen po restartu:</b><br>"
      "Graf buffer je v PSRAM &mdash; je RAM, ne Flash &mdash; se izgubi ob vsakem resetu."
      " To je normalno. History se začne znova zbirati od zagona.</p>"
      "<p><b>Web UI ni dosegljiv:</b><br>"
      "Preveri <code>wifi_config.h</code> (SSID, geslo, statični IP, gateway)."
      " Ping statični IP. Preizkusi <code>http://fan.local</code> (mDNS)."
      " Serial log pokaže WiFi connect status in IP.</p>"
      "<p><b>OTA ne uspe:</b><br>"
      "Preveri da je <code>.bin</code> datoteka pravilna (ne <code>.elf</code>)."
      " Preizkusi z manjšo datoteko &mdash; če je firmware večji od app particije"
      " bo OTA zavrnjen. Particijska shema je v <code>partitions_16mb_ota.csv</code>.</p>"
      "</div>");

    // ── 22. REFERENCE IN VIRI ────────────────────────────────────────────────
    H("<div class=\"card\">"
      "<div class=\"card-title\">Reference in viri</div>"
      "<p class=\"dim\">"
      "ESP32-S3 TZT N16R8 datasheet: <a href=\"https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/\">Espressif ESP32-S3 docs</a><br>"
      "WeAct ePaper 2.9\" B/W: <a href=\"https://github.com/WeActStudio/WeActStudio.EpaperModule\">WeActStudio GitHub</a><br>"
      "SHT30 datasheet: Sensirion SHT3x-DIS<br>"
      "INA219 datasheet: Texas Instruments INA219<br>"
      "Open-Meteo API: <a href=\"https://open-meteo.com\">open-meteo.com</a> &mdash; brezplačen, brez API ključa<br>"
      "uPlot knjižnica: <a href=\"https://github.com/leeoniya/uPlot\">leeoniya/uPlot</a> &mdash; MIT licenca<br>"
      "ezTime knjižnica: <a href=\"https://github.com/ropg/ezTime\">ropg/ezTime</a><br>"
      "ESPAsyncWebServer: me-no-dev/ESPAsyncWebServer<br>"
      "ArduinoJson: <a href=\"https://arduinojson.org\">arduinojson.org</a><br>"
      "LR7843 MOSFET modul: N-channel 100V 30A MOSFET with gate driver<br>"
      "Sunrise formula: Duffett-Smith, &quot;Practical Astronomy with your Calculator&quot;<br>"
      "Intel PWM standard: 4-Wire Pulse Width Modulation (PWM) Controlled Fans specification<br>"
      "Referenčni projekt: vent_SEW (arhitekturni vzorec: globals, graph_store, web)<br>"
      "<br>"
      "fancontrol projekt &mdash; 2026. Firmware v" FW_VERSION ".<br>"
      "GitHub: <a href=\"https://github.com/S53BL/fancontrol\">github.com/S53BL/fancontrol</a>"
      "</p>"
      "</div>");

    H("</main></body></html>");

    return html;
}

// ---------------------------------------------------------------------------
// registerAboutHandler() — registrira /about handler na podanem serverju
// ---------------------------------------------------------------------------
void registerAboutHandler(AsyncWebServer& server) {
    server.on("/about", HTTP_GET, [](AsyncWebServerRequest *request) {
        String html = buildAboutPage();
        AsyncWebServerResponse *resp = request->beginResponse(
            200, "text/html; charset=UTF-8", html);
        resp->addHeader("Cache-Control", "no-cache");
        request->send(resp);
    });
}
